[tool.black]
line-length = 79

[tool.flake8]
exclude = ['.git', '__pycache__', '.venv', '.vscode', '.dockerignore', '.gitignore']
ignore = ['W503', 'E501']
max-line-length = 79
max-complexity = 10

[tool.isort]
profile = "black"
